-- MySQL Script generated by MySQL Workbench
-- Mon Mar 12 21:15:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_fact_quantum
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_fact_quantum` ;

-- -----------------------------------------------------
-- Schema db_fact_quantum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_fact_quantum` DEFAULT CHARACTER SET utf8 ;
USE `db_fact_quantum` ;

-- -----------------------------------------------------
-- Table `db_fact_quantum`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`company` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NOT NULL,
  `comercial_name` VARCHAR(180) NOT NULL,
  `emission_code` INT(3) NOT NULL,
  `tax_year` INT(6) NOT NULL,
  `url` VARCHAR(255) NULL,
  `phone` VARCHAR(80) NULL,
  `address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`branch_office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`branch_office` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`branch_office` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NOT NULL,
  `phone` VARCHAR(80) NULL,
  `adress` VARCHAR(80) NULL,
  `email` VARCHAR(60) NULL,
  `emission_point` INT(3) NOT NULL,
  `company_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_branch_office_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_branch_office_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`users` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(180) NOT NULL,
  `username_canonical` VARCHAR(180) NULL,
  `email` VARCHAR(80) NULL,
  `email_canonical` VARCHAR(80) NULL,
  `enabled` TINYINT(1) NULL,
  `salt` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `last_login` DATETIME NULL,
  `password_requested_at` DATETIME NULL,
  `first_name` VARCHAR(180) NULL,
  `last_name` VARCHAR(180) NULL,
  `phone_number` VARCHAR(80) NULL,
  `company_id` INT(11) NOT NULL,
  `branch_office_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_company_idx` (`company_id` ASC),
  INDEX `fk_users_branch_office1_idx` (`branch_office_id` ASC),
  CONSTRAINT `fk_users_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_branch_office1`
    FOREIGN KEY (`branch_office_id`)
    REFERENCES `db_fact_quantum`.`branch_office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`client` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`client` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstlast_name_social_reason` VARCHAR(255) NOT NULL,
  `comercial_name` VARCHAR(255) NULL,
  `phone` VARCHAR(80) NULL,
  `address` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `company_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_client_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`invoice` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`invoice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `principal_code` INT(10) NULL,
  `concept` VARCHAR(255) NULL,
  `referral_code` INT(15) NULL,
  `amount` DECIMAL(15,4) NOT NULL,
  `sub_total` DECIMAL(15,4) NULL,
  `total_discount` DECIMAL(15,4) NULL,
  `sub_total_discount` DECIMAL(15,4) NULL,
  `ice_total` DECIMAL(15,4) NULL,
  `total_iva` DECIMAL(15,4) NULL,
  `invoice_total` DECIMAL(15,4) NULL,
  `xml_generated` BLOB NULL,
  `auth_code` VARCHAR(49) NULL,
  `auth_date` DATETIME NULL,
  `emission_type` INT(1) NOT NULL,
  `environment_type` INT(1) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `branch_office_id` INT(11) NOT NULL,
  `company_id` INT(11) NOT NULL,
  `client_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoice_branch_office1_idx` (`branch_office_id` ASC),
  INDEX `fk_invoice_company1_idx` (`company_id` ASC),
  INDEX `fk_invoice_client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_invoice_branch_office1`
    FOREIGN KEY (`branch_office_id`)
    REFERENCES `db_fact_quantum`.`branch_office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `db_fact_quantum`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`aditional_field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`aditional_field` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`aditional_field` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NOT NULL,
  `value` VARCHAR(180) NOT NULL,
  `invoice_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aditional_field_invoice1_idx` (`invoice_id` ASC),
  CONSTRAINT `fk_aditional_field_invoice1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `db_fact_quantum`.`invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`parameter` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`parameter` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `logo` VARCHAR(255) NOT NULL,
  `system_current_version` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`entity` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`entity` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`entity_masterdata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`entity_masterdata` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`entity_masterdata` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `description` VARCHAR(255) NULL,
  `field` VARCHAR(5) NULL,
  `status` TINYINT(1) NOT NULL,
  `entity_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entity_masterdata_entity1_idx` (`entity_id` ASC),
  CONSTRAINT `fk_entity_masterdata_entity1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `db_fact_quantum`.`entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`mail_configuration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`mail_configuration` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`mail_configuration` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `host_server` VARCHAR(60) NOT NULL,
  `ip_address` VARCHAR(20) NOT NULL,
  `incoming_port` INT(5) NOT NULL,
  `outgoing_port` INT(5) NOT NULL,
  `subject` VARCHAR(255) NULL,
  `body` VARCHAR(255) NULL,
  `leyend` VARCHAR(255) NULL,
  `incoming_server_type_id` INT(11) NOT NULL,
  `incoming_security_type_id` INT(11) NOT NULL,
  `outgoing_server_type_id` INT(11) NOT NULL,
  `outgoing_security_type_id` INT(11) NOT NULL,
  `mail_identification_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mail_configuration_entity_masterdata1_idx` (`incoming_server_type_id` ASC),
  INDEX `fk_mail_configuration_entity_masterdata2_idx` (`incoming_security_type_id` ASC),
  INDEX `fk_mail_configuration_entity_masterdata3_idx` (`outgoing_server_type_id` ASC),
  INDEX `fk_mail_configuration_entity_masterdata4_idx` (`outgoing_security_type_id` ASC),
  INDEX `fk_mail_configuration_entity_masterdata5_idx` (`mail_identification_type_id` ASC),
  CONSTRAINT `fk_mail_configuration_entity_masterdata1`
    FOREIGN KEY (`incoming_server_type_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mail_configuration_entity_masterdata2`
    FOREIGN KEY (`incoming_security_type_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mail_configuration_entity_masterdata3`
    FOREIGN KEY (`outgoing_server_type_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mail_configuration_entity_masterdata4`
    FOREIGN KEY (`outgoing_security_type_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mail_configuration_entity_masterdata5`
    FOREIGN KEY (`mail_identification_type_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`branch_parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`branch_parameter` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`branch_parameter` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `branch_office_id` INT(11) NOT NULL,
  `parameter_id` INT(11) NOT NULL,
  `mail_configuration_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_branch_parameter_branch_office1_idx` (`branch_office_id` ASC),
  INDEX `fk_branch_parameter_parameter1_idx` (`parameter_id` ASC),
  INDEX `fk_branch_parameter_mail_configuration1_idx` (`mail_configuration_id` ASC),
  CONSTRAINT `fk_branch_parameter_branch_office1`
    FOREIGN KEY (`branch_office_id`)
    REFERENCES `db_fact_quantum`.`branch_office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_parameter_parameter1`
    FOREIGN KEY (`parameter_id`)
    REFERENCES `db_fact_quantum`.`parameter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_parameter_mail_configuration1`
    FOREIGN KEY (`mail_configuration_id`)
    REFERENCES `db_fact_quantum`.`mail_configuration` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`audit_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`audit_user` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`audit_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `concept` VARCHAR(255) NOT NULL,
  `company_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_audit_user_company1_idx` (`company_id` ASC),
  INDEX `fk_audit_user_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_audit_user_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit_user_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_fact_quantum`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`client_identification_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`client_identification_type` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`client_identification_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `identification` VARCHAR(20) NOT NULL,
  `client_id` INT(11) NOT NULL,
  `identification_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_identification_type_client1_idx` (`client_id` ASC),
  INDEX `fk_client_identification_type_entity_masterdata1_idx` (`identification_type_id` ASC),
  CONSTRAINT `fk_client_identification_type_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `db_fact_quantum`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_identification_type_entity_masterdata1`
    FOREIGN KEY (`identification_type_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`company_parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`company_parameter` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`company_parameter` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NOT NULL,
  `parameter_id` INT(11) NOT NULL,
  `mail_configuration_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_parameter_company1_idx` (`company_id` ASC),
  INDEX `fk_company_parameter_parameter1_idx` (`parameter_id` ASC),
  INDEX `fk_company_parameter_mail_configuration1_idx` (`mail_configuration_id` ASC),
  CONSTRAINT `fk_company_parameter_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_parameter_parameter1`
    FOREIGN KEY (`parameter_id`)
    REFERENCES `db_fact_quantum`.`parameter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_parameter_mail_configuration1`
    FOREIGN KEY (`mail_configuration_id`)
    REFERENCES `db_fact_quantum`.`mail_configuration` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`plan` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`plan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NOT NULL,
  `document_count` INT NOT NULL,
  `duration` INT NOT NULL,
  `price` DECIMAL(15,4) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`company_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`company_plan` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`company_plan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `current_counter` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `company_id` INT(11) NOT NULL,
  `plan_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_plan_company1_idx` (`company_id` ASC),
  INDEX `fk_company_plan_plan1_idx` (`plan_id` ASC),
  CONSTRAINT `fk_company_plan_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_plan_plan1`
    FOREIGN KEY (`plan_id`)
    REFERENCES `db_fact_quantum`.`plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`correlative_document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`correlative_document` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`correlative_document` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `increment_number` INT(10) NOT NULL,
  `serie` VARCHAR(10) NULL,
  `company_id` INT(11) NOT NULL,
  `document_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_correlative_document_company1_idx` (`company_id` ASC),
  INDEX `fk_correlative_document_entity_masterdata1_idx` (`document_type_id` ASC),
  CONSTRAINT `fk_correlative_document_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_correlative_document_entity_masterdata1`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`country_currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`country_currency` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`country_currency` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `currency_id` INT(11) NOT NULL,
  `country_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_country_currency_entity_masterdata1_idx` (`currency_id` ASC),
  INDEX `fk_country_currency_entity_masterdata2_idx` (`country_id` ASC),
  CONSTRAINT `fk_country_currency_entity_masterdata1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_currency_entity_masterdata2`
    FOREIGN KEY (`country_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`country_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`country_language` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`country_language` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `country_id` INT(11) NOT NULL,
  `language_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_country_language_entity_masterdata1_idx` (`country_id` ASC),
  INDEX `fk_country_language_entity_masterdata2_idx` (`language_id` ASC),
  CONSTRAINT `fk_country_language_entity_masterdata1`
    FOREIGN KEY (`country_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_language_entity_masterdata2`
    FOREIGN KEY (`language_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`country_tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`country_tax` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`country_tax` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `value` DECIMAL(15,4) NOT NULL,
  `country_id` INT(11) NOT NULL,
  `tax_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_country_tax_entity_masterdata1_idx` (`country_id` ASC),
  INDEX `fk_country_tax_entity_masterdata2_idx` (`tax_id` ASC),
  CONSTRAINT `fk_country_tax_entity_masterdata1`
    FOREIGN KEY (`country_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_tax_entity_masterdata2`
    FOREIGN KEY (`tax_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`dispatcher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`dispatcher` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`dispatcher` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(180) NULL,
  `last_name` VARCHAR(180) NULL,
  `phone` VARCHAR(80) NULL,
  `address` VARCHAR(255) NULL,
  `email` VARCHAR(60) NULL,
  `dni` VARCHAR(50) NULL,
  `passport` VARCHAR(50) NULL,
  `ruc` VARCHAR(50) NULL,
  `company_id` INT(11) NOT NULL,
  `identificacion_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dispatcher_company1_idx` (`company_id` ASC),
  INDEX `fk_dispatcher_entity_masterdata1_idx` (`identificacion_type_id` ASC),
  CONSTRAINT `fk_dispatcher_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dispatcher_entity_masterdata1`
    FOREIGN KEY (`identificacion_type_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`guide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`guide` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`guide` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NULL,
  `principal_code` INT(10) NULL,
  `description` VARCHAR(255) NULL,
  `company_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_guide_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_guide_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`product` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NULL,
  `principal_code` VARCHAR(50) NOT NULL,
  `auxiliary_code` VARCHAR(50) NULL,
  `description` VARCHAR(255) NULL,
  `unit_price` DECIMAL(15,4) NULL,
  `unit_cost` DECIMAL(15,4) NULL,
  `is_purchase_active` TINYINT(1) NOT NULL,
  `is_sale_active` TINYINT(1) NOT NULL,
  `min_stock` DECIMAL(15,4) NOT NULL,
  `max_stock` DECIMAL(15,4) NULL,
  `company_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_product_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`guide_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`guide_product` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`guide_product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `guide_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_guide_product_guide1_idx` (`guide_id` ASC),
  INDEX `fk_guide_product_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_guide_product_guide1`
    FOREIGN KEY (`guide_id`)
    REFERENCES `db_fact_quantum`.`guide` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guide_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_fact_quantum`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`invoice_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`invoice_line` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`invoice_line` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `count` DECIMAL(15,4) NOT NULL,
  `unit_price` DECIMAL(15,4) NOT NULL,
  `discount` DECIMAL(15,4) NULL,
  `invoice_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoice_line_invoice1_idx` (`invoice_id` ASC),
  INDEX `fk_invoice_line_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_invoice_line_invoice1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `db_fact_quantum`.`invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_line_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_fact_quantum`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`invoice_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`invoice_payment` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`invoice_payment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `document_number` VARCHAR(20) NOT NULL,
  `mount` DECIMAL(15,4) NOT NULL,
  `invoice_id` INT(11) NOT NULL,
  `payment_type` INT(11) NOT NULL,
  `bank_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoice_paiment_invoice1_idx` (`invoice_id` ASC),
  INDEX `fk_invoice_paiment_entity_masterdata1_idx` (`payment_type` ASC),
  INDEX `fk_invoice_paiment_entity_masterdata2_idx` (`bank_id` ASC),
  CONSTRAINT `fk_invoice_paiment_invoice1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `db_fact_quantum`.`invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_paiment_entity_masterdata1`
    FOREIGN KEY (`payment_type`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_paiment_entity_masterdata2`
    FOREIGN KEY (`bank_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`product_tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`product_tax` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`product_tax` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_id` INT(11) NOT NULL,
  `country_tax_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_tax_product1_idx` (`product_id` ASC),
  INDEX `fk_product_tax_country_tax1_idx` (`country_tax_id` ASC),
  CONSTRAINT `fk_product_tax_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_fact_quantum`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_tax_country_tax1`
    FOREIGN KEY (`country_tax_id`)
    REFERENCES `db_fact_quantum`.`country_tax` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`role_module_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`role_module_permission` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`role_module_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_id` INT(11) NOT NULL,
  `module_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_module_permission_entity_masterdata1_idx` (`role_id` ASC),
  INDEX `fk_role_module_permission_entity_masterdata2_idx` (`module_id` ASC),
  INDEX `fk_role_module_permission_entity_masterdata3_idx` (`permission_id` ASC),
  CONSTRAINT `fk_role_module_permission_entity_masterdata1`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_module_permission_entity_masterdata2`
    FOREIGN KEY (`module_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_module_permission_entity_masterdata3`
    FOREIGN KEY (`permission_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`tax_document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`tax_document` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`tax_document` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `denomination_invoce_doc` INT(2) NOT NULL,
  `denomination_retention` INT(2) NULL,
  `tax_document_retention` INT(10) NULL,
  `emission_date` DATETIME NOT NULL,
  `amount` DECIMAL(15,4) NOT NULL,
  `concept` VARCHAR(255) NULL,
  `xml_generated` BLOB NULL,
  `auth_code` VARCHAR(49) NULL,
  `auth_date` DATETIME NULL,
  `emission_type` INT(1) NOT NULL,
  `environment_type` INT(1) NOT NULL,
  `invoice_id` INT(11) NOT NULL,
  `documetn_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tax_document_invoice1_idx` (`invoice_id` ASC),
  INDEX `fk_tax_document_entity_masterdata1_idx` (`documetn_type_id` ASC),
  CONSTRAINT `fk_tax_document_invoice1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `db_fact_quantum`.`invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tax_document_entity_masterdata1`
    FOREIGN KEY (`documetn_type_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`trasportation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`trasportation` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`trasportation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `principal_code` VARCHAR(10) NULL,
  `concept` VARCHAR(255) NULL,
  `company_id` INT(11) NOT NULL,
  `dispatcher_id` INT(11) NOT NULL,
  `trasportation_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trasportation_company1_idx` (`company_id` ASC),
  INDEX `fk_trasportation_entity_masterdata1_idx` (`trasportation_type_id` ASC),
  INDEX `fk_trasportation_dispatcher1_idx` (`dispatcher_id` ASC),
  CONSTRAINT `fk_trasportation_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `db_fact_quantum`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trasportation_entity_masterdata1`
    FOREIGN KEY (`trasportation_type_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trasportation_dispatcher1`
    FOREIGN KEY (`dispatcher_id`)
    REFERENCES `db_fact_quantum`.`dispatcher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`system_configuration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`system_configuration` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`system_configuration` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fact_quantum`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fact_quantum`.`user_role` ;

CREATE TABLE IF NOT EXISTS `db_fact_quantum`.`user_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_users1_idx` (`users_id` ASC),
  INDEX `fk_user_role_entity_masterdata1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_fact_quantum`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_entity_masterdata1`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_fact_quantum`.`entity_masterdata` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
